name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # รัน SonarQube Scanner
      - name: Run SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=chirapatsae_api_reserver_room
            -Dsonar.sources=.
            -Dsonar.tests=tests
            -Dsonar.test.inclusions=tests/**/*.spec.js,tests/**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  zap-scan:
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

      - name: Build Docker image for API
        run: docker build -t my-api .

      - name: Run API container
        run: docker run -d -p 3000:3000 --name api my-api

      - name: Wait for API to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:3000/health && break
            echo "Waiting for API..."
            sleep 3
          done

      - name: Run ZAP full scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: http://host.docker.internal:3000

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_json.json
            report_md.md
            report_html.html

      - name: Cleanup API container
        run: docker rm -f api || true

